# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(max_length=30)),
                ('fecha_inclusion', models.DateField()),
                ('enlace', models.URLField()),
                ('tipo', models.CharField(max_length=20)),
                ('habitaciones', models.IntegerField()),
                ('m2', models.IntegerField()),
                ('otros', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.IntegerField()),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mueb.Inmueble')),
            ],
        ),
    ]
