# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-22 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mueb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='con_garaje',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
