# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-21 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mueb', '0002_inmueble_codigo_pagina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='id',
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='codigo_pagina',
            field=models.CharField(db_index=True, max_length=40, primary_key=True, serialize=False),
        ),
    ]
