# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mueb', '0002_inmueble_con_garaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.URLField()),
                ('habitaciones', models.IntegerField()),
                ('m2', models.IntegerField()),
                ('descr', models.CharField(max_length=240)),
            ],
            options={
                'db_table': 'favoritos',
            },
        ),
        migrations.CreateModel(
            name='PrecioFavorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.IntegerField()),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mueb.Inmueble')),
            ],
            options={
                'db_table': 'preciosfavoritos',
            },
        ),
    ]
