# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-21 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mueb', '0003_auto_20160521_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='descr',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
    ]
