# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mueb', '0004_auto_20170721_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciofavorito',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mueb.Favorito'),
        ),
    ]
